### ISSUE TITLE
Template validation error for workload.template.yaml

### ISSUE THREAD

**Issue by sshvans** [aws-quickstart/quickstart-workshop-labs#1]
### Issue
workload.template.yaml shows validation error. 

### Output
$ aws cloudformation validate-template --template-body file://templates/workload.template.yaml

An error occurred (ValidationError) when calling the ValidateTemplate operation: Template error: every value of the context object of every Fn::Sub object must be a string or a function that returns a string

**Comment by tonynv** [comment]
Fixed in https://github.com/aws-quickstart/quickstart-workshop-labs/commit/9237855a7abba29353bc9e19ef19a28ec6839650
