### ISSUE TITLE
Issues when running the quickstart-workshop

### ISSUE THREAD

**Issue by edselg** [aws-quickstart/quickstart-workshop-labs#2]
A number of issues are shown by the TaskCat validation when running the Sep 18 quickstart-workshop with the Mar 11 quickstart-workshop-labs.

**Issues**
Here is the list of errors and warnings:

$ taskcat test run -p qs-workshop 

...

version 0.9.8
[WARN   ] : failed to load config from /home/ec2-user/environment/qs-workshop/.taskcat.yml
[WARN   ] : config is in a legacy format, support for which will be dropped in a future version. a new format config (.taskcat.yml) will been placed in your project_root
[WARN   ] : overrides file /home/ec2-user/.aws/taskcat_global_override.json is in legacy format, support for this format will be deprecated in a future version.
[WARN   ] : Converting overrides to new format and saving in /home/ec2-user/.taskcat.yml
[INFO   ] : Lint passed for test lab-master-vpc on template /home/ec2-user/environment/qs-workshop/submodules/quickstart-linux-bastion/templates/linux-bastion.template
[ERROR  ] : Lint detected issues for test lab-master-vpc on template /home/ec2-user/environment/qs-workshop/templates/workload.template.yaml:
[WARN   ] :     line 73 [2001] [Check if Parameters are Used] Parameter PrivateSubnet1ID not used.
[WARN   ] :     line 76 [2001] [Check if Parameters are Used] Parameter PrivateSubnet2ID not used.
[WARN   ] :     line 88 [2001] [Check if Parameters are Used] Parameter VPCCIDR not used.
[ERROR  ] :     line 148 [3002] [Resource properties are valid] Invalid Property
                                                      Resources/WebServerGroup/Properties/NotificationConfiguration
[ERROR  ] :     line 161 [3016] [Check the configuration of a resources UpdatePolicy] Value for MinInstancesInService must be of type Integer
[ERROR  ] :     line 162 [3016] [Check the configuration of a resources UpdatePolicy] Value for MaxBatchSize must be of type Integer
[ERROR  ] :     line 164 [3016] [Check the configuration of a resources UpdatePolicy] Value for WaitOnResourceSignals must be of type Boolean
[ERROR  ] :     line 257 [3012] [Check resource properties values] Property Resources/WebServerScaleUpPolicy/Properties/ScalingAdjustment should be of type Integer
[ERROR  ] :     line 264 [3012] [Check resource properties values] Property Resources/WebServerScaleDownPolicy/Properties/ScalingAdjustment should be of type Integer
[ERROR  ] :     line 272 [3012] [Check resource properties values] Property Resources/WebServerCPUAlarmHigh/Properties/Period should be of type Integer
[ERROR  ] :     line 273 [3012] [Check resource properties values] Property Resources/WebServerCPUAlarmHigh/Properties/EvaluationPeriods should be of type Integer
[ERROR  ] :     line 274 [3012] [Check resource properties values] Property Resources/WebServerCPUAlarmHigh/Properties/Threshold should be of type Double
[ERROR  ] :     line 288 [3012] [Check resource properties values] Property Resources/WebServerCPUAlarmLow/Properties/Period should be of type Integer
[ERROR  ] :     line 289 [3012] [Check resource properties values] Property Resources/WebServerCPUAlarmLow/Properties/EvaluationPeriods should be of type Integer
[ERROR  ] :     line 290 [3012] [Check resource properties values] Property Resources/WebServerCPUAlarmLow/Properties/Threshold should be of type Double
[ERROR  ] :     line 315 [3012] [Check resource properties values] Property Resources/ALBListener/Properties/Port should be of type Integer
[ERROR  ] :     line 333 [3012] [Check resource properties values] Property Resources/WebServerSecurityGroup/Properties/SecurityGroupIngress/0/FromPort should be of type Integer
[ERROR  ] :     line 334 [3012] [Check resource properties values] Property Resources/WebServerSecurityGroup/Properties/SecurityGroupIngress/0/ToPort should be of type Integer
[ERROR  ] :     line 337 [3012] [Check resource properties values] Property Resources/WebServerSecurityGroup/Properties/SecurityGroupIngress/1/FromPort should be of type Integer
[ERROR  ] :     line 338 [3012] [Check resource properties values] Property Resources/WebServerSecurityGroup/Properties/SecurityGroupIngress/1/ToPort should be of type Integer
[WARN   ] : Lint detected issues for test lab-master-vpc on template /home/ec2-user/environment/qs-workshop/submodules/quickstart-aws-vpc/templates/aws-vpc.template:
[WARN   ] :     line 172 [2001] [Check if Parameters are Used] Parameter KeyPairName not used.
[WARN   ] :     line 177 [2001] [Check if Parameters are Used] Parameter NATInstanceType not used.
[WARN   ] :     line 420 [8001] [Check if Conditions are Used] Condition GovCloudCondition not used
[WARN   ] : Lint detected issues for test lab-master-vpc on template /home/ec2-user/environment/qs-workshop/templates/master.template.yaml:
[WARN   ] :     line 140 [3005] [Check obsolete DependsOn configuration for Resources] Obsolete DependsOn on resource (VPCStack), dependency already enforced by a "Fn:GetAtt" at Resources/BastionStack/Properties/Parameters/PublicSubnet1ID/Fn::GetAtt
[WARN   ] :     line 140 [3005] [Check obsolete DependsOn configuration for Resources] Obsolete DependsOn on resource (VPCStack), dependency already enforced by a "Fn:GetAtt" at Resources/BastionStack/Properties/Parameters/PublicSubnet2ID/Fn::GetAtt
[WARN   ] :     line 140 [3005] [Check obsolete DependsOn configuration for Resources] Obsolete DependsOn on resource (VPCStack), dependency already enforced by a "Fn:GetAtt" at Resources/BastionStack/Properties/Parameters/VPCID/Fn::GetAtt
[WARN   ] :     line 171 [3005] [Check obsolete DependsOn configuration for Resources] Obsolete DependsOn on resource (VPCStack), dependency already enforced by a "Fn:GetAtt" at Resources/WorkloadStack/Properties/Parameters/PrivateSubnet1ID/Fn::GetAtt
[WARN   ] :     line 171 [3005] [Check obsolete DependsOn configuration for Resources] Obsolete DependsOn on resource (VPCStack), dependency already enforced by a "Fn:GetAtt" at Resources/WorkloadStack/Properties/Parameters/PrivateSubnet2ID/Fn::GetAtt
[WARN   ] :     line 171 [3005] [Check obsolete DependsOn configuration for Resources] Obsolete DependsOn on resource (VPCStack), dependency already enforced by a "Fn:GetAtt" at Resources/WorkloadStack/Properties/Parameters/PublicSubnet1ID/Fn::GetAtt
[WARN   ] :     line 171 [3005] [Check obsolete DependsOn configuration for Resources] Obsolete DependsOn on resource (VPCStack), dependency already enforced by a "Fn:GetAtt" at Resources/WorkloadStack/Properties/Parameters/PublicSubnet2ID/Fn::GetAtt
[WARN   ] :     line 171 [3005] [Check obsolete DependsOn configuration for Resources] Obsolete DependsOn on resource (VPCStack), dependency already enforced by a "Fn:GetAtt" at Resources/WorkloadStack/Properties/Parameters/VPCID/Fn::GetAtt
[WARN   ] :     line 171 [3005] [Check obsolete DependsOn configuration for Resources] Obsolete DependsOn on resource (VPCStack), dependency already enforced by a "Fn:GetAtt" at Resources/WorkloadStack/Properties/Parameters/VPCCIDR/Fn::GetAtt
[ERROR  ] : Lint failed with errors
(vpy36) workshop:~/environment $ 

**Fix**
The errors can be fixed by using the corresponding datatype for the properties:
* Using integer and boolean values by removing the single quotes around them
* Using NotificationConfigurations are shown in the example in the user guide:
  * https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/quickref-autoscaling.html#scenario-as-notification

Once the errors are fixed, TaskCat will continue and run the CloudFormation template.

Warning 3005 (W3005) "Obsolete DependsOn" can be resolved by removing the DependsOn reference from webserver.master.template.yaml and bastionstack.master.template.yaml.

CloudFormation already behaves as having DependsOn when Fn:GetAttr is used.
See: https://aws.amazon.com/blogs/devops/optimize-aws-cloudformation-templates/

Notes:
* I found an additional issue on the creation of the BastionStack. This issue is shown when running the lab (TaskCat, and CodePipeline), however, it is not seen when creating the Linux Bastion (https://docs.aws.amazon.com/quickstart/latest/linux-bastion/welcome.html).

```
Received 0 SUCCESS signal(s) out of 1. Unable to satisfy 100% MinSuccessfulInstancesPercent requirement
```
Debugging showed that issue happened because an AccessDenied error 403 when accessing the bastion_bootstrap.sh script as an S3 (HTTPS).

Login onto the Linux Bastion Host confirms the 403 error when accessing the S3 resource.

**Comment by vsnyc** [comment]
This is no longer relevant.
